### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by Kryptortio** [Glodenox/twitch-chat-monitor#28]
I think this could work well as an extension. It should not be very difficult to make a [Webextension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) that makes it easy to use this chat. I'm thinking you would just have a button with a dropdown that gives you three choices. 

* Embed (replace normal chat when on Twitch, maybe leave chatbox intact)
* Floating chat on top of current page as a movable resizable iframe
* New tab (just open as is in a new window)

Btw, @Glodenox  cool little project you made I forked your repo and added a bunch of features
https://github.com/Kryptortio/twitch-chat-monitor
Primarily I was just planning on adding a filter for excessive chat spam but then I got some more ideas. I left open branches so feel free to pull anything you want into the main repo (some more testing first might be a good idea).

**Comment by Glodenox** [comment]
Thanks! I'll try to look into your additions next week to see what I can merge :)

As for the extension idea:
I haven't got a lot of experience with writing extensions. But from what I've seen, that shouldn't be too hard, indeed. I consider the idea to be outside of the scope of this project though. It might be something to do in a separate project by relying on some of the resources created here, but I'd prefer to keep this project focused on the idea of showing the Twitch chat on a big screen.

It could also be created as a userscript, but that's not as user-friendly to use and has much worse discoverability.

**Comment by Glodenox** [comment]
FYI: I've implemented a rudimentary chatbox that allows you to send messages. tmi.js supports this, as well as pretty much any other action you can do in the Twitch chat. I might look into implementing some of the modding functions here as well.

**Comment by Kryptortio** [comment]
Ahh I see you've added a lot of the features/fixes from my fork now, nice! Looks like you've added these:

- Automatically filter twitch url if included in channel
- Cross out messages before joining new channel
- Channel can be added to url using ?c=[channelname]
- Sometimes clicks pass through settings window
- Fix support for non a-z0-9 chars in messages
- Prevent multiple deletes of same message

And a more "proper" way of enabling chatting than just embedding a Twitch chat. 

I would suggest you consider something like "fading of spammy messages (and move them down)" as well though (inspired by [ChitChat](https://chitchat.ma.pe/)). I find it super useful when you use it for reading chats of very popular streamers. With your feature for combining repeated messages it really clears things up and you can much more easily follow what's happening. 

I think BTTV & FFZ support can also help since it's easier to gloss over emotes than text as your eyes identify those faster. Popular chats is also why I added the feature to popup a message by clicking it so you have time to read it or copy something important like an url. I also added options to move timestamps to the right to have less things for your eyes to scan when the chat is moving fast and an option for combo counter to the left so you have time to see it.
