### ISSUE TITLE
VIP highlighting

### ISSUE THREAD

**Issue by paul-lrr** [Glodenox/twitch-chat-monitor#40]
Currently Mod names are a different color, but it would be handy to also mark VIP users (since visibility is usually the reason for granting VIP). I think a new name color would be a good way of doing it (to differentiate it from the full line highlight that is used for message and username highlighting). I guess it would also require a new color entry in the various themes.

**Comment by Glodenox** [comment]
Distinguishing by user type would indeed be a useful addition. I'd probably broaden it towards [all user types](https://help.twitch.tv/s/article/twitch-chat-badges-guide) then.

At the moment there is already the option to show the user's badges, but that makes reading the chat quite a bit harder.

**Comment by paul-lrr** [comment]
In my original nifty chat monitor script, I just added the user type(s) as classes to the message div, so they could be easily targeted with css for whatever type of highlighting is required. eg. `message.vip {background-color:green}` or `message.vip .username {color:pink}` etc

Maybe it would make sense to even put all of a user's badges as classes of the message div for maximum flexibility. That way an end user could use custom CSS rules to format it however they want

**Comment by Glodenox** [comment]
That would somewhat be the approach I'd take here, indeed. [The CSS style for moderator users](https://github.com/Glodenox/twitch-chat-monitor/blob/master/style.css#L107) works like that, but has a CSS variable to store its color in. One thing I'll have to take into account would be that some people may have multiple "badges". But that's just a matter of properly sorting the CSS statements (last declared selector has precedence).

While people will be able to override the CSS themselves this way, I don't think this will be done a lot though, if the custom allows you to adjust those colors already.

**Comment by Glodenox** [comment]
Implemented in [v1.12.0](https://github.com/Glodenox/twitch-chat-monitor/releases/tag/v1.12.0)
