### ISSUE TITLE
Support links containing @

### ISSUE THREAD

**Issue by Gaelan** [Glodenox/twitch-chat-monitor#47]
All* the cool kids are on Mastodon these days, which means Mastodon links are showing up in Desert Bus chat; these look like https://kind.social/@desertbus.

Currently, twitch-chat-monitor doesn't recognize @ as a valid character in a  URL, so Mastodon links don't work.

*some of

**Comment by Glodenox** [comment]
I had already noticed the issue pop up, but had indeed forgotten about that. Thanks for the reminder!
